import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { AlertTriangle, Mic, Activity, Save, Download, FileText, ArrowLeft } from 'lucide-react';
import jsPDF from 'jspdf';

const DiagnosisResult = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [diagnosis, setDiagnosis] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  
  const messages = location.state?.messages || [];
  const symptoms = location.state?.symptoms || "General health inquiry";
  const preloadedDiagnosis = location.state?.preloadedDiagnosis;

  useEffect(() => {
    if (preloadedDiagnosis) {
      setDiagnosis(preloadedDiagnosis);
      setIsLoading(false);
    } else {
      generateAIDiagnosis();
    }
  }, [preloadedDiagnosis]);

  const generateAIDiagnosis = async () => {
    setIsLoading(true);
    
    try {
      // Simulate AI diagnosis generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const diagnosisResult = analyzeSymptoms(symptoms);
      setDiagnosis(diagnosisResult);
    } catch (error) {
      console.error('Error generating diagnosis:', error);
      setDiagnosis({
        condition: "Error in Analysis",
        probability: "Unable to determine",
        riskLevel: "Unknown",
        riskColor: "bg-gray-500",
        description: "There was an error analyzing your symptoms. Please try again.",
        causes: "System error occurred during analysis.",
        nextSteps: ["Please try again later", "Contact support if the issue persists"]
      });
    } finally {
      setIsLoading(false);
    }
  };

  const analyzeSymptoms = (symptomText) => {
    const text = symptomText.toLowerCase();
    
    // AI-based symptom analysis simulation
    if (text.includes('fever') || text.includes('temperature')) {
      return {
        condition: "Viral Fever",
        probability: "85%",
        riskLevel: "Medium",
        riskColor: "bg-yellow-500",
        description: "Based on your symptoms, there's an 85% chance you have a viral fever. This is commonly caused by viral infections and typically resolves within 3-7 days with proper care.",
        causes: "Viral infections, including common cold viruses, flu viruses, or other seasonal pathogens. The fever indicates your immune system is actively fighting the infection.",
        nextSteps: [
          "Rest and stay well-hydrated with water, herbal teas, and clear broths",
          "Take acetaminophen or ibuprofen to reduce fever and discomfort",
          "Use cool compresses on forehead and wrists",
          "Monitor temperature every 4-6 hours",
          "Seek medical attention if fever exceeds 103°F (39.4°C) or persists beyond 5 days",
          "Watch for warning signs: difficulty breathing, severe headache, or persistent vomiting",
          
          "Disclaimer: This report is generated by MediChat AI and is for informational ",
          "purposes only ad it is suggested one not prescribed..",
        ]
      };
    }
    
    if (text.includes('cold') || text.includes('cough') || text.includes('sneez')) {
      return {
        condition: "Common Cold",
        probability: "80%",
        riskLevel: "Low",
        riskColor: "bg-green-500",
        description: "There's an 80% chance your symptoms are due to a common viral cold. Less likely causes include mild flu (12%) or allergies (8%).",
        causes: "Colds are caused mainly by rhinoviruses, spread through droplets or surface contact. Symptoms often include sneezing, runny nose, sore throat, and mild fever.",
        nextSteps: [
          "Rest and drink plenty of fluids",
          "Use warm salt-water gargles for sore throat",
          "Take paracetamol for fever or pain (if safe for you)",
          "Wash hands often to prevent spread",
          "Use a humidifier or breathe steam from hot shower",
          "See a doctor if fever is high, symptoms worsen after a week, or you have trouble breathing"
        ]
      };
    }
    
    if (text.includes('headache') || text.includes('head')) {
      return {
        condition: "Tension Headache",
        probability: "70%",
        riskLevel: "Low",
        riskColor: "bg-green-500",
        description: "Based on your symptoms, there's a 70% likelihood of tension headaches, often caused by stress, poor posture, or muscle tension. Migraines (20%) and cluster headaches (10%) are less likely.",
        causes: "Tension headaches are typically caused by muscle contractions in the head and neck region, often triggered by stress, anxiety, poor posture, or eye strain.",
        nextSteps: [
          "Apply cold or warm compress to head and neck",
          "Practice relaxation techniques and stress management",
          "Ensure adequate sleep (7-9 hours per night)",
          "Stay hydrated and maintain regular meals",
          "Take over-the-counter pain relievers as directed",
          "Seek medical attention for sudden severe headaches, headaches with fever, or changes in headache pattern"
        ]
      };
    }
    
    // Default diagnosis
    return {
      condition: "General Health Assessment",
      probability: "Assessment Complete",
      riskLevel: "Low",
      riskColor: "bg-blue-500",
      description: "Based on the information provided, I've completed a preliminary health assessment. Your symptoms appear to be manageable with proper self-care.",
      causes: "Various factors could contribute to your current symptoms including lifestyle, stress, minor infections, or temporary health variations.",
      nextSteps: [
        "Monitor your symptoms and keep a health diary",
        "Maintain good hygiene and healthy lifestyle habits",
        "Stay hydrated and get adequate rest",
        "Consider stress reduction techniques",
        "Consult healthcare provider if symptoms persist or worsen",
        "Schedule regular check-ups for preventive care"
      ]
    };
  };

  const saveDiagnosis = () => {
    if (!diagnosis) return;
    
    const savedData = {
      diagnosis: diagnosis,
      symptoms: symptoms,
      date: new Date().toISOString().split('T')[0],
      timestamp: new Date()
    };
    
    try {
      const existingHistory = JSON.parse(localStorage.getItem('medicalHistory') || '[]');
      existingHistory.unshift(savedData);
      localStorage.setItem('medicalHistory', JSON.stringify(existingHistory));
      alert('Diagnosis saved to your medical history!');
    } catch (error) {
      console.error('Error saving diagnosis:', error);
      alert('Error saving diagnosis. Please try again.');
    }
  };

  const downloadReport = (format) => {
    if (!diagnosis) return;
    
    const currentDate = new Date();
    const dateStr = currentDate.toISOString().split('T')[0];
    const timeStr = currentDate.toLocaleTimeString();
    
    if (format === 'pdf') {
      downloadEnhancedPDFReport(dateStr, timeStr);
    } else if (format === 'txt') {
      downloadTextReport(dateStr, timeStr);
    }
  };

  const downloadTextReport = (dateStr, timeStr) => {
    const reportContent = `
╔══════════════════════════════════════════════════════════════╗
║                        MEDICAL REPORT                        ║
║                     Created by MediChat                      ║
╚══════════════════════════════════════════════════════════════╝

Generated Date: ${dateStr}
Generated Time: ${timeStr}

═══════════════════════════════════════════════════════════════

PATIENT SYMPTOMS:
${symptoms}

═══════════════════════════════════════════════════════════════

AI MEDICAL ANALYSIS:

Likely Condition: ${diagnosis?.condition || 'Unknown'}
Confidence Level: ${diagnosis?.probability || 'Unknown'}
Risk Level: ${diagnosis?.riskLevel || 'Unknown'}

ANALYSIS:
${diagnosis?.description || 'No analysis available'}

CAUSES:
${diagnosis?.causes || 'No causes available'}

RECOMMENDED NEXT STEPS:
${diagnosis?.nextSteps?.map((step, index) => `${index + 1}. ${step}`).join('\n') || 'No recommendations available'}

═══════════════════════════════════════════════════════════════

DISCLAIMER:
This report is generated by MediChat AI and is for informational 
purposes only. It should not replace professional medical advice, 
diagnosis, or treatment. Always consult with qualified healthcare 
providers for medical decisions.

═══════════════════════════════════════════════════════════════

Report ID: MC-${Date.now()}
Created by: MediChat - AI Medical Assistant
Website: Your MediChat Application
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MediChat_Report_${dateStr}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // ENHANCED DIRECT PDF DOWNLOAD - Like ChatGPT
  const downloadEnhancedPDFReport = (dateStr, timeStr) => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.width;
    const pageHeight = pdf.internal.pageSize.height;
    let yPosition = 20;

    // Helper function to add text with word wrapping
    const addText = (text, x, y, fontSize = 12, fontStyle = 'normal', maxWidth = pageWidth - 40) => {
      pdf.setFontSize(fontSize);
      pdf.setFont('helvetica', fontStyle);
      
      const lines = pdf.splitTextToSize(text, maxWidth);
      pdf.text(lines, x, y);
      return y + (lines.length * fontSize * 0.4);
    };

    // Add page function
    const checkNewPage = (requiredSpace = 30) => {
      if (yPosition > pageHeight - requiredSpace) {
        pdf.addPage();
        yPosition = 20;
      }
    };

    // Header with MediChat branding
    pdf.setFillColor(229, 62, 62); // Medical red color
    pdf.rect(0, 0, pageWidth, 50, 'F');
    
    // White text on red background
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(28);
    pdf.setFont('helvetica', 'bold');
    pdf.text('🩺 MediChat', 20, 25);
    
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'normal');
    pdf.text('AI Medical Assessment Report', 20, 35);
    
    pdf.setFontSize(12);
    pdf.text('Professional Medical Analysis • Powered by Advanced AI', 20, 45);

    // Reset text color to black
    pdf.setTextColor(0, 0, 0);
    yPosition = 70;

    // Report metadata box
    pdf.setFillColor(248, 249, 250);
    pdf.rect(15, yPosition - 5, pageWidth - 30, 25, 'F');
    pdf.setDrawColor(229, 62, 62);
    pdf.setLineWidth(0.5);
    pdf.rect(15, yPosition - 5, pageWidth - 30, 25, 'S');
    
    yPosition = addText(`Report ID: MC-${Date.now()}`, 20, yPosition + 5, 10, 'bold');
    yPosition = addText(`Generated: ${dateStr} at ${timeStr}`, 20, yPosition, 10);
    yPosition = addText(`Condition: ${diagnosis?.condition || 'General Assessment'}`, 20, yPosition, 10);
    yPosition += 20;

    checkNewPage();

    // Patient Symptoms Section
    pdf.setFillColor(255, 245, 245);
    pdf.rect(15, yPosition - 5, pageWidth - 30, 30, 'F');
    pdf.setDrawColor(229, 62, 62);
    pdf.setLineWidth(2);
    pdf.line(15, yPosition - 5, 15, yPosition + 25);
    
    yPosition = addText('📋 PATIENT SYMPTOMS & CHIEF COMPLAINT', 20, yPosition + 5, 16, 'bold');
    yPosition += 5;
    yPosition = addText(symptoms, 20, yPosition, 12, 'normal', pageWidth - 50);
    yPosition += 20;

    checkNewPage();

    // AI Analysis Section
    pdf.setFillColor(245, 245, 255);
    pdf.rect(15, yPosition - 5, pageWidth - 30, 40, 'F');
    pdf.setDrawColor(229, 62, 62);
    pdf.setLineWidth(2);
    pdf.line(15, yPosition - 5, 15, yPosition + 35);
    
    yPosition = addText('🤖 AI MEDICAL ANALYSIS & DIAGNOSIS', 20, yPosition + 5, 16, 'bold');
    yPosition += 8;
    yPosition = addText(`Primary Condition: ${diagnosis?.condition || 'Unknown'}`, 20, yPosition, 14, 'bold');
    yPosition = addText(`Confidence Level: ${diagnosis?.probability || 'Unknown'}`, 20, yPosition, 12);
    yPosition = addText(`Risk Assessment: ${diagnosis?.riskLevel || 'Unknown'} Risk Level`, 20, yPosition, 12);
    yPosition += 20;

    checkNewPage();

    // Clinical Analysis Section
    yPosition = addText('🔍 CLINICAL ANALYSIS & ASSESSMENT', 20, yPosition, 16, 'bold');
    yPosition += 8;
    
    // Analysis box
    pdf.setFillColor(247, 250, 252);
    const analysisHeight = Math.max(30, Math.ceil((diagnosis?.description?.length || 0) / 80) * 5 + 10);
    pdf.rect(15, yPosition - 5, pageWidth - 30, analysisHeight, 'F');
    pdf.setDrawColor(66, 153, 225);
    pdf.setLineWidth(2);
    pdf.line(15, yPosition - 5, 15, yPosition + analysisHeight - 5);
    
    yPosition = addText('Medical Analysis:', 20, yPosition, 12, 'bold');
    yPosition = addText(diagnosis?.description || 'No analysis available', 20, yPosition, 11, 'normal', pageWidth - 50);
    yPosition += 10;
    
    yPosition = addText('Probable Causes & Pathophysiology:', 20, yPosition, 12, 'bold');
    yPosition = addText(diagnosis?.causes || 'No causes identified', 20, yPosition, 11, 'normal', pageWidth - 50);
    yPosition += 20;

    checkNewPage(60);

    // Recommendations Section
    yPosition = addText('📝 CLINICAL RECOMMENDATIONS & TREATMENT PLAN', 20, yPosition, 16, 'bold');
    yPosition += 8;
    
    if (diagnosis?.nextSteps?.length > 0) {
      diagnosis.nextSteps.forEach((step, index) => {
        checkNewPage(20);
        
        // Recommendation box
        pdf.setFillColor(240, 255, 244);
        const stepHeight = Math.max(15, Math.ceil(step.length / 70) * 4 + 8);
        pdf.rect(15, yPosition - 5, pageWidth - 30, stepHeight, 'F');
        pdf.setDrawColor(72, 187, 120);
        pdf.setLineWidth(2);
        pdf.line(15, yPosition - 5, 15, yPosition + stepHeight - 5);
        
        // Step number circle
        pdf.setFillColor(72, 187, 120);
        pdf.circle(25, yPosition + 5, 5, 'F');
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text((index + 1).toString(), 23, yPosition + 7);
        pdf.setTextColor(0, 0, 0);
        
        yPosition = addText(step, 35, yPosition + 2, 11, 'normal', pageWidth - 70);
        yPosition += 8;
      });
    } else {
      yPosition = addText('No specific recommendations available at this time.', 20, yPosition, 11);
    }

    yPosition += 20;
    checkNewPage(80);

    // Medical Disclaimer
    pdf.setFillColor(255, 243, 205);
    pdf.rect(15, yPosition - 5, pageWidth - 30, 60, 'F');
    pdf.setDrawColor(255, 193, 7);
    pdf.setLineWidth(2);
    pdf.rect(15, yPosition - 5, pageWidth - 30, 60, 'S');
    
    yPosition = addText('⚠️ IMPORTANT MEDICAL DISCLAIMER', 20, yPosition + 5, 14, 'bold');
    yPosition += 5;
    
    const disclaimerText = `This medical report has been generated by MediChat's artificial intelligence system for informational and educational purposes only. This analysis should not be considered as a substitute for professional medical advice, diagnosis, or treatment. Always consult with qualified healthcare professionals for confirmation of any medical condition, appropriate diagnostic testing, personalized treatment recommendations, emergency medical situations, and prescription medications or medical procedures.`;
    
    yPosition = addText(disclaimerText, 20, yPosition, 10, 'normal', pageWidth - 50);
    yPosition += 30;

    // Footer
    if (yPosition > pageHeight - 40) {
      pdf.addPage();
      yPosition = 20;
    }

    pdf.setFillColor(45, 55, 72);
    pdf.rect(0, yPosition, pageWidth, 40, 'F');
    
    pdf.setTextColor(229, 62, 62);
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('🩺 MediChat', 20, yPosition + 15);
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Created by MediChat - Advanced AI Medical Assistant', 20, yPosition + 25);
    
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Powered by Artificial Intelligence • © ${new Date().getFullYear()} MediChat. All rights reserved.`, 20, yPosition + 35);

    // DIRECT DOWNLOAD - This automatically saves the PDF file
    pdf.save(`MediChat_Medical_Report_${dateStr}_${Date.now()}.pdf`);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-white p-6">
        {/* Header with Back Button */}
        <div className="flex items-center mb-8">
          <button 
            onClick={() => navigate(-1)}
            className="mr-4 p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <ArrowLeft className="w-6 h-6 text-gray-600" />
          </button>
          <h1 className="text-3xl font-bold">
            <span className="text-medical-red">Medi</span>
            <span className="text-black">Chat</span>
          </h1>
        </div>
        
        <div className="max-w-4xl mx-auto text-center">
          <div className="bg-gray-100 border border-gray-300 rounded-lg p-8">
            <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-medical-red mx-auto mb-4"></div>
            <h3 className="text-xl font-bold text-medical-red mb-2">🧠 AI Analyzing Your Symptoms...</h3>
            <p className="text-gray-600">Please wait while I process your medical information and generate a comprehensive diagnosis.</p>
          </div>
        </div>
      </div>
    );
  }

  // Show error state if no diagnosis
  if (!diagnosis) {
    return (
      <div className="min-h-screen bg-white p-6">
        {/* Header with Back Button */}
        <div className="flex items-center mb-8">
          <button 
            onClick={() => navigate(-1)}
            className="mr-4 p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <ArrowLeft className="w-6 h-6 text-gray-600" />
          </button>
          <h1 className="text-3xl font-bold">
            <span className="text-medical-red">Medi</span>
            <span className="text-black">Chat</span>
          </h1>
        </div>
        
        <div className="max-w-4xl mx-auto text-center">
          <div className="bg-red-50 border border-red-200 rounded-lg p-8">
            <h3 className="text-xl font-bold text-red-600 mb-2">Error Loading Diagnosis</h3>
            <p className="text-gray-600 mb-4">Sorry, we couldn't load your diagnosis. Please try again.</p>
            <button 
              onClick={() => navigate('/chat')}
              className="bg-medical-red text-white px-6 py-3 rounded-full font-medium hover:bg-red-600 transition-colors"
            >
              Start New Consultation
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white p-6">
      {/* Header with Back Button */}
      <div className="flex items-center mb-8">
        <button 
          onClick={() => navigate(-1)}
          className="mr-4 p-2 hover:bg-gray-100 rounded-full transition-colors"
        >
          <ArrowLeft className="w-6 h-6 text-gray-600" />
        </button>
        <h1 className="text-3xl font-bold">
          <span className="text-medical-red">Medi</span>
          <span className="text-black">Chat</span>
        </h1>
      </div>

      {/* Question */}
      <div className="max-w-4xl mx-auto mb-6">
        <div className="bg-gray-200 inline-block px-6 py-3 rounded-2xl rounded-tr-none ml-auto">
          <p className="text-gray-800">{symptoms}</p>
        </div>
      </div>

      {/* AI Diagnosis Result */}
      <div className="max-w-4xl mx-auto mb-8">
        <div className="bg-gray-100 border border-gray-300 rounded-lg p-6">
          {/* AI Analysis Header with Download Options */}
          <div className="flex items-center justify-between mb-4 flex-wrap gap-4">
            <h2 className="text-medical-red font-bold text-xl">🤖 AI Medical Analysis</h2>
            <div className="flex items-center gap-2 flex-wrap">
              <button 
                onClick={saveDiagnosis}
                className="bg-blue-600 text-white px-4 py-2 rounded-full text-sm font-medium flex items-center hover:bg-blue-700 transition-colors"
              >
                <Save className="w-4 h-4 mr-1" />
                Save Report
              </button>
              
              {/* Download Dropdown - PDF & TXT Only */}
              <div className="relative group">
                <button className="bg-green-600 text-white px-4 py-2 rounded-full text-sm font-medium flex items-center hover:bg-green-700 transition-colors">
                  <Download className="w-4 h-4 mr-1" />
                  Download Report
                </button>
                <div className="absolute right-0 mt-2 w-56 bg-white border border-gray-300 rounded-lg shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-10">
                  <button
                    onClick={() => downloadReport('pdf')}
                    className="w-full px-4 py-3 text-left hover:bg-gray-100 flex items-center text-gray-700 rounded-t-lg border-b border-gray-100"
                  >
                    <FileText className="w-5 h-5 mr-3 text-red-600" />
                    <div>
                      <div className="font-semibold">Download as PDF</div>
                      <div className="text-xs text-gray-500">Professional medical report</div>
                    </div>
                  </button>
                  <button
                    onClick={() => downloadReport('txt')}
                    className="w-full px-4 py-3 text-left hover:bg-gray-100 flex items-center text-gray-700 rounded-b-lg"
                  >
                    <FileText className="w-5 h-5 mr-3 text-blue-600" />
                    <div>
                      <div className="font-semibold">Download as Text</div>
                      <div className="text-xs text-gray-500">Simple text format</div>
                    </div>
                  </button>
                </div>
              </div>
            </div>
          </div>
          
          {/* Condition & Probability */}
          <div className="mb-4">
            <h3 className="text-medical-red font-bold text-lg mb-2">📋 Likely Condition: {diagnosis?.condition || 'Unknown'}</h3>
            <p className="text-gray-700 mb-2">
              <strong>Confidence Level:</strong> {diagnosis?.probability || 'Unknown'}
            </p>
          </div>

          {/* Risk Level */}
          <div className="flex items-center mb-4">
            <h3 className="text-medical-red font-bold text-lg mr-3">⚠️ Risk Level:</h3>
            <div className="flex items-center">
              <div className="w-6 h-6 bg-medical-red rounded-full mr-2 flex items-center justify-center">
                <div className="w-2 h-2 bg-white rounded-full"></div>
              </div>
              <span className={`${diagnosis?.riskColor || 'bg-gray-500'} text-white px-4 py-1 rounded-full text-sm font-medium`}>
                {diagnosis?.riskLevel || 'Unknown'}
              </span>
            </div>
          </div>

          {/* Description */}
          <div className="mb-6">
            <h4 className="text-medical-red font-bold text-lg mb-3">🔍 Analysis:</h4>
            <p className="text-gray-700 mb-4">{diagnosis?.description || 'No analysis available'}</p>
            <p className="text-gray-700 mb-4">{diagnosis?.causes || 'No causes available'}</p>
          </div>

          {/* Next Steps */}
          <div>
            <h4 className="text-medical-red font-bold text-lg mb-3">📝 Recommended Next Steps:</h4>
            <ul className="list-disc list-inside text-gray-700 space-y-2">
              {diagnosis?.nextSteps?.length > 0 ? (
                diagnosis.nextSteps.map((step, index) => (
                  <li key={index}>{step}</li>
                ))
              ) : (
                <li>No recommendations available at this time.</li>
              )}
            </ul>
          </div>
        </div>
      </div>

      {/* Navigation Buttons */}
      <div className="max-w-4xl mx-auto flex justify-center gap-4">
        <button 
          onClick={() => navigate('/history')}
          className="bg-gray-800 text-white px-6 py-3 rounded-full font-medium hover:bg-gray-700 transition-colors"
        >
          View History
        </button>
        <button 
          onClick={() => navigate('/chat')}
          className="bg-medical-red text-white px-6 py-3 rounded-full font-medium hover:bg-red-600 transition-colors"
        >
          New Consultation
        </button>
      </div>
    </div>
  );
};

export default DiagnosisResult;
